# Generated by Django 6.0.1 on 2026-01-22 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título atrativo para o imóvel', max_length=200, verbose_name='Título do Anúncio')),
                ('descricao', models.TextField(help_text='Descrição detalhada do imóvel', verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Valor do aluguel mensal', max_digits=10, verbose_name='Preço Mensal (R$)')),
                ('bairro', models.CharField(choices=[('centro', 'Centro'), ('jardim_botanico', 'Jardim Botânico'), ('vila_nova', 'Vila Nova'), ('parque_industrial', 'Parque Industrial'), ('santa_rita', 'Santa Rita'), ('sao_francisco', 'São Francisco'), ('bela_vista', 'Bela Vista'), ('jardim_europa', 'Jardim Europa')], max_length=50, verbose_name='Bairro')),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('kitnet', 'Kitnet'), ('apartamento', 'Apartamento'), ('quarto', 'Quarto')], max_length=20, verbose_name='Tipo de Imóvel')),
                ('telefone_contato', models.CharField(help_text='Formato: (DD) 9XXXX-XXXX', max_length=20, verbose_name='Telefone/WhatsApp')),
                ('foto_principal', models.ImageField(help_text='Imagem principal do imóvel', upload_to='imoveis/', verbose_name='Foto Principal')),
                ('ativo', models.BooleanField(default=True, help_text='Imóvel disponível para aluguel?', verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imoveis', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
                'ordering': ['-criado_em'],
            },
        ),
    ]
