# Generated by Django 6.0.1 on 2026-01-27 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='visualizacoes',
            field=models.IntegerField(default=0, help_text='Contador de visualizações do imóvel', verbose_name='Visualizações'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='bairro',
            field=models.CharField(choices=[('centro', 'Centro'), ('nova_corrente', 'Nova Corrente'), ('aeroporto_i', 'Aeroporto I'), ('aeroporto_ii', 'Aeroporto II'), ('vermelhao', 'Vermelhão'), ('sincerino', 'Sincerino'), ('vila_nova', 'Vila Nova')], max_length=50, verbose_name='Bairro'),
        ),
        migrations.CreateModel(
            name='ImagemImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imoveis/galeria/', verbose_name='Imagem')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='imoveis.imovel', verbose_name='Imóvel')),
            ],
            options={
                'verbose_name': 'Imagem do Imóvel',
                'verbose_name_plural': 'Imagens dos Imóveis',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LOCADOR', 'Locador'), ('LOCATARIO', 'Locatário')], default='LOCATARIO', max_length=20, verbose_name='Tipo de Usuário')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone/WhatsApp')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
    ]
